created domain classes
DavidCaidas/MoviesAndShowsApi pull request #5
Opened 2022-11-09 15:16 UTC by DavidCaidas

## Description de la tarea

created all domain classes for future use

## ¿Cómo se ha implementado?

created classes following the xml

## Keywords

domain, classes 

## Objetivos

implementar correctamente las clases para el dominio

## Criterios de Evaluación

2022-11-09 16:16 UTC, jmperezra requested changes
David, tienes que prestar mucha atención en el formato de los namings, es muy importante que sigas el criterio que aplicamos en Kotlin (mismo que en java y mayoría de lenguajes).

2022-11-09 16:16 UTC, jmperezra commented on app/src/main/java/com/example/movies_and_shows_api/domain/GetMoviesFeedUseCase.kt
> +class GetMoviesFeedUseCase (
Por favor, cuida el tabulado entre líneas de código, hay mucho espacio entre ellas, puedes tomar como ejemplo el código que hacemos en clase. Además, recuerda usar Ctrl + Alt + l (ele) para el autoformato.

2022-11-09 16:16 UTC, jmperezra commented on app/src/main/java/com/example/movies_and_shows_api/domain/Repositories.kt
> +        fun getMovieById(MovieId: String): movie?
please, cuida el naming de los parámetros, nunca nunca van en mayúscula. Ante la duda, fíjate en el código que realizamos en clase.

2022-11-09 16:16 UTC, jmperezra commented on app/src/main/java/com/example/movies_and_shows_api/domain/movies.kt
> +data class movie( val id: String,
Por favor, revisa el naming, las clases van siempre en mayúsculas (como en Java).

2022-11-09 16:16 UTC, jmperezra commented on app/src/main/java/com/example/movies_and_shows_api/domain/movies.kt
> +                   val Poster:String )
Parámetro en mayúsculas??

2022-11-17 07:04 UTC, josem-perram approved these changes
La PR está bien, sólo un comentario de duda, puedes hacer merge.

2022-11-17 07:04 UTC, josem-perram commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMoviesFeedUseCase.kt
> +    private val MovieRepository: MovieRepository = TODO()
TODO() por qué añades esto??

2022-11-17 07:53 UTC, DavidCaidas commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMoviesFeedUseCase.kt
> +    private val MovieRepository: MovieRepository = TODO()
porque me estaba dando un fallo que no conocía y al poner eso se me quitó

2022-11-17 07:53 UTC, merged