created remote Api classes
DavidCaidas/MoviesAndShowsApi pull request #6
Opened 2022-11-09 15:33 UTC by DavidCaidas

## Description de la tarea

creadas correctamente las clases remotas para movies

## ¿Cómo se ha implementado?

creando las clases siguiendo el mismo orden que en proyectos anteriores

## Keywords

remote, api, apimodel

## Objetivos

usar de manera correcta los archivos api, apimodel y el uso de datos de manera remota

## Criterios de Evaluación

2022-11-09 16:19 UTC, jmperezra requested changes
David, arrastras errores: namings, los nombres de las clases, variables, métodos, etc.

Por otro lado, los comentarios de las PR son muy anémicos, es decir, ofrece poca información sobre el propósito de la PR.

2022-11-09 16:19 UTC, jmperezra commented on app/src/main/java/com/example/movies_and_shows_api/data/ApiClient.kt
> +    fun getmovies(): List<moviesApiModel> {
Errores en general, namings, por favor, haz una revisión general porque hay varios errores de este tipo y es lo principal, salta mucho a la vista.

2022-11-17 07:29 UTC, josem-perram approved these changes
David, una vez cambies el nombre de la clase puedes hacer el merge sin solicitar otra revisión.

2022-11-17 07:29 UTC, josem-perram commented on app/src/main/java/com/movies/movies_and_shows_api/data/movieDataRepository.kt
> +class SuperHeroDataRepository(
Ainsss el copy&paste 😅

2022-11-17 07:29 UTC, josem-perram commented on app/src/main/java/com/movies/movies_and_shows_api/data/remote/api/moviesApiMapper.kt
> +import com.movies.movies_and_shows_api.domain.Movie
Te digo lo mismo que a Rafa, los paquetes no pueden llevar underscore. Tienen que ir todo junto y en minúsculas.

2022-11-17 07:29 UTC, josem-perram commented on app/src/main/java/com/movies/movies_and_shows_api/data/remote/api/moviesApiMapper.kt
> +fun moviesApiModel.toDomain(): Movie {
moviesApiModel debería ser el nombre de una clase, y este nombre debería empezar en mayúsculas. Te paso por Teams un pdf con la convención de nombres para que lo tengas a mano.

2022-11-17 07:29 UTC, josem-perram commented on app/src/main/java/com/movies/movies_and_shows_api/data/remote/api/moviesApiRemoteDataSource.kt
> +class moviesApiRemoteDataSource(val apiClient: ApiClient) : MoviesRemoteDataSource {
Las clases deberían empezar en mayúsculas.

2022-11-17 08:07 UTC, DavidCaidas commented on app/src/main/java/com/movies/movies_and_shows_api/data/movieDataRepository.kt
> +class SuperHeroDataRepository(
lo peor es que era una clase duplicada que tenia que cogí como referencia

2022-11-17 08:07 UTC, merged