Created all remote api classes, Fixed Naming
DavidCaidas/MoviesAndShowsApi pull request #7
Opened 2022-11-11 15:24 UTC by DavidCaidas

## Description de la tarea

implemented all the archives and views for the Api models and the remote control, fixed the naming from anterior pull requests

## ¿Cómo se ha implementado?

created detail class for movies and changed all the names in the classes for correct typing and naming 

## Keywords

changes,naming,classes,detail class

## Objetivos

updrade the correct use for naming classes and data and implement a detail class for the proyect

## Criterios de Evaluación

2022-11-17 07:33 UTC, josem-perram approved these changes
David, las PR deberían hacer sólo unan cosa, en este caso deberíamos haber hecho una PR para la llamada a remoto y otra para solucionar los problemas de namings.

Por otro lado, seguimos arrastrando problemas de namings, por favor, revisa el pdf que te he enviado por Teams.

2022-11-17 07:33 UTC, josem-perram commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMovieDetailUseCase.kt
> +        val Movie = movieRepository.getMovieById(movieId)!!
Las variables deberían ir en minúsculas.

2022-11-17 07:33 UTC, josem-perram commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMovieDetailUseCase.kt
> +    data class movieDetail(
Las clases deberían empezar con mayúsculas.

2022-11-17 07:33 UTC, josem-perram commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMoviesFeedUseCase.kt
> +
hay que formatear el código (ctrl + alt + L) aquí hay espacio extra que no aporta nada.

2022-11-17 07:33 UTC, josem-perram commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMoviesFeedUseCase.kt
> +        val Movies = movieRepository.getMovie()
lo mismo aquí, variables en minúsculas.

2022-11-17 14:35 UTC, DavidCaidas commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMovieDetailUseCase.kt
> +        val Movie = movieRepository.getMovieById(movieId)!!
lo cambio y vuelco a platear la PR

2022-11-17 14:36 UTC, DavidCaidas commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMovieDetailUseCase.kt
> +    data class movieDetail(
ahorita lo cambio

2022-11-17 14:36 UTC, DavidCaidas commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMoviesFeedUseCase.kt
> +
ahora lo cambio

2022-11-17 14:37 UTC, DavidCaidas commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMoviesFeedUseCase.kt
> +        val Movies = movieRepository.getMovie()
a cambiarlo voy, ahora pido otra PR

2022-11-18 14:35 UTC, jmperezra requested changes
@DavidCaidas quedan algunos namings por resolver.

2022-11-18 14:35 UTC, jmperezra commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMovieDetailUseCase.kt
> +        val Movie = movieRepository.getMovieById(movieId)!!
@DavidCaidas la conversación ha quedado marcada como resuelta pero sigue estando el error, la variable tiene un formato de nombre incorrecto: Movie en vez de movie.

2022-11-18 14:54 UTC, DavidCaidas commented on app/src/main/java/com/movies/movies_and_shows_api/domain/GetMovieDetailUseCase.kt
> +        val Movie = movieRepository.getMovieById(movieId)!!
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHorita mismo lo reviso y cambio

2022-11-24 12:45 UTC, josem-perram approved these changes

2022-11-24 15:40 UTC, merged